/**
 * RBAC Type Definitions
 */

export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  REVIEWER = 'REVIEWER',
  PROGRAMMER = 'PROGRAMMER',
  DEVELOPER = 'DEVELOPER',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  VISITOR = 'VISITOR',
}

export enum Permission {
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER = 'UPDATE_USER',
  VIEW_USER = 'VIEW_USER',
  MODIFY_USER = 'MODIFY_USER',
  VIEW_USERS = 'VIEW_USERS',
  CREATE_PROJECT = 'CREATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  VIEW_PROJECT = 'VIEW_PROJECT',
  VIEW_PROJECTS = 'VIEW_PROJECTS',
  MODIFY_PROJECT = 'MODIFY_PROJECT',
  VIEW_REVIEWS = 'VIEW_REVIEWS',
  CREATE_REVIEW = 'CREATE_REVIEW',
  MODIFY_REVIEW = 'MODIFY_REVIEW',
  MODIFY_CONFIG = 'MODIFY_CONFIG',
  VIEW_CONFIG = 'VIEW_CONFIG',
  EXPORT_REPORT = 'EXPORT_REPORT',
}

export interface RBACUser {
  id: string;
  username: string;
  role: Role;
  permissions?: Permission[];
}

